FROM caddy:2.8.4-builder AS builder
RUN xcaddy build --with github.com/crowdsecurity/caddy-bouncer/v2

FROM caddy:2.8.4
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY Caddyfile.prod.tmpl /etc/caddy/Caddyfile.prod.tmpl
COPY Caddyfile.local /etc/caddy/Caddyfile.local
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
